### ISSUE TITLE
manpage not generated on HEAD

### ISSUE THREAD

**Issue by anarcat** [DaveDavenport/xininfo#5]
it looks like the bits that were present in 0.14.11 to generate a manpage:

```
$(BUILD_DIR)/$(DOC_DIR)/$(MANPAGE): $(DOC_DIR)/$(MANPAGE_SOURCE)
        $(info geerate manpage $^-> $@)
        $(QUIET)md2man-roff $^ > $@
```

... are gone from the new build system.

what the heck is md2man-roff anyways?

**Comment by DaveDavenport** [comment]
guess, the name gives it away.

This will be all fixed in next release.

**Comment by anarcat** [comment]
what i meant is more "where can i find it?" but I have found it in https://sunaku.github.io/md2man
